name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Create output zip
        uses: vimtor/action-zip@v1
        with:
          files: Instances/ JoobsPack-Lite.zip
          recursive: false
          dest: JoobsPack-Lite.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: cranberriez/joobsmodpack