name: Build Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Upload Zip File
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: Instances/JoobsPack-Lite.zip

      - name: Grab Zip File For Release
        uses: actions/download-artifact@v3
        with:
          name: release-artifact

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}/download-guide.md
          files: ${{ github.workspace }}/*.zip